import jsPDF from 'jspdf';
import { format } from 'date-fns';

import { LOGO_BASE64 } from './logo';
import { LETTERHEAD_BASE64 } from './letterheadBase64';

export const generateRequestPDF = (request, userProfile) => {
    const doc = new jsPDF();

    // Brand Colors
    const primaryColor = [250, 204, 21]; // Yellow-400 equivalent
    const secondaryColor = [17, 24, 39]; // Gray-900 equivalent

    // --- Header ---
    doc.addImage(LOGO_BASE64, 'PNG', 160, 10, 30, 30);
    doc.setDrawColor(0, 0, 0);
    doc.setLineWidth(0.5);
    doc.line(20, 45, 190, 45);

    // --- Body ---
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`DATE: ${format(new Date(), 'MMMM d, yyyy')}`, 160, 60, { align: 'right' });

    // Recipient Info
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("To:", 20, 60);
    doc.setFont("helvetica", "normal");
    doc.text(request.name || "Staff Member", 20, 66);
    doc.text(request.email || userProfile?.email || "", 20, 72);
    if (userProfile?.staff_id) {
        doc.text(`Staff ID: ${userProfile.staff_id}`, 20, 78);
    }

    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 85, 190, 85);

    // Subject
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    const statusText = request.status === 'Approved' ? 'APPROVAL' : 'REJECTION';
    doc.text(`${request.type ? request.type.toUpperCase() : 'REQUEST'} ${statusText}`, 20, 100);

    // Content Logic
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");

    let contentY = 120;

    if (request.status === 'Approved') {
        const typeLabel = request.type === 'Leave' ? `${request.leave_type} Leave` : request.type;

        doc.text(`Dear ${(request.name || 'Member').split(' ')[0]},`, 20, contentY);
        contentY += 10;

        doc.text(`We are pleased to inform you that your request for ${typeLabel} has been APPROVED.`, 20, contentY);
        contentY += 10;

        if (request.type === 'Leave' && request.dates) {
            doc.text(`Authorized Dates: ${request.dates.length} days`, 20, contentY);
            contentY += 6;
            const dateRange = `${format(new Date(request.dates[0]), 'MMM d, yyyy')} - ${format(new Date(request.dates[request.dates.length - 1]), 'MMM d, yyyy')}`;
            doc.text(`(${dateRange})`, 20, contentY);
            contentY += 10;
        } else if (request.amount) {
            doc.text(`Authorized Amount: KES ${request.amount.toLocaleString()}`, 20, contentY);
            contentY += 10;
        }

        doc.text("Please retain this document for your records.", 20, contentY + 10);

    } else {
        doc.text(`Dear ${request.name?.split(' ')[0] || 'Member'},`, 20, contentY);
        contentY += 10;

        doc.text(`We regret to inform you that your request has been DECLINED at this time.`, 20, contentY);
        contentY += 10;

        doc.text("If you have any questions, please contact the HR administration.", 20, contentY + 10);
    }

    // --- Footer ---
    const footerY = 250;
    doc.setDrawColor(200, 200, 200);
    doc.line(20, footerY, 190, footerY);

    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text("This document was automatically generated by the POT OF JOLLOF LTD System.", 105, footerY + 10, { align: 'center' });
    doc.text(`Reference ID: ${request.id}`, 105, footerY + 15, { align: 'center' });

    // Save or Return
    if (userProfile?.returnBase64) {
        return doc.output('datauristring').split(',')[1]; // Return raw base64
    } else {
        doc.save(`${request.type || 'Request'}_${request.status || 'Update'}_${format(new Date(), 'yyyyMMdd')}.pdf`);
    }
};

export const generateReceiptPDF = (data) => {
    const doc = new jsPDF();

    // Brand Colors
    const primaryColor = [250, 204, 21];
    const secondaryColor = [17, 24, 39];

    // --- Header (Ink Saving: No solid rectangle) ---

    // Logo (Added)
    doc.addImage(LOGO_BASE64, 'PNG', 185, 2, 16, 16);

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("POT OF JOLLOF LTD", 20, 13);

    // --- Meta Data ---
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);

    // Right side: Date and Receipt #
    doc.text(`DATE: ${format(new Date(data.date), 'MMMM d, yyyy')}`, 190, 60, { align: 'right' });
    if (data.reference) {
        doc.text(`REF: ${data.reference}`, 190, 66, { align: 'right' });
    }

    // Left side: Supplier Info
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Received From:", 20, 60);
    doc.setFont("helvetica", "normal");
    doc.text(data.supplier, 20, 66);
    doc.text(`Payment Method: ${data.paymentMethod}`, 20, 72);

    // --- Table ---
    // We need autoTable for the list
    import('jspdf-autotable').then(({ default: autoTable }) => {
        autoTable(doc, {
            startY: 85,
            head: [['Description', 'Qty', 'Unit Price', 'Total']],
            body: data.items.map(item => [
                item.description,
                item.quantity,
                `KES ${item.price.toLocaleString()}`,
                `KES ${(item.quantity * item.price).toLocaleString()}`
            ]),
            foot: [['', '', 'Grand Total', `KES ${data.total.toLocaleString()}`]],
            theme: 'striped',
            headStyles: { fillColor: secondaryColor, textColor: [255, 255, 255] },
            footStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: 'bold' },
            styles: { fontSize: 10, cellPadding: 3 },
            columnStyles: {
                0: { cellWidth: 'auto' }, // Description
                1: { cellWidth: 20 },     // Qty
                2: { cellWidth: 40 },     // Price
                3: { cellWidth: 40, halign: 'right' } // Total
            }
        });

        // --- Footer ---
        const finalY = doc.lastAutoTable.finalY + 30;

        doc.setDrawColor(200, 200, 200);
        doc.line(20, finalY, 190, finalY);

        doc.setFontSize(8);
        doc.setTextColor(100, 100, 100);
        doc.text("This document was automatically generated by the POT OF JOLLOF LTD System.", 105, finalY + 10, { align: 'center' });
        doc.text(`Generated on ${format(new Date(), 'PPpp')}`, 105, finalY + 15, { align: 'center' });

        doc.save(`Receipt_${data.supplier.replace(/\s+/g, '_')}_${data.date}.pdf`);
    });
};

export const generateWarningPDF = (data, options = {}) => {
    const doc = new jsPDF();
    const primaryColor = [220, 38, 38]; // Red-600

    // --- Header ---
    doc.addImage(LOGO_BASE64, 'PNG', 160, 10, 30, 30);
    doc.setDrawColor(0, 0, 0);
    doc.setLineWidth(0.5);
    doc.line(20, 45, 190, 45);

    // Body
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`DATE: ${format(new Date(), 'MMMM d, yyyy')}`, 190, 60, { align: 'right' });

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("To:", 20, 60);
    doc.setFont("helvetica", "normal");
    doc.text(data.staffName, 20, 66);
    doc.text(data.staffEmail, 20, 72);

    doc.setDrawColor(200, 200, 200);
    doc.line(20, 85, 190, 85);

    const headerTitle = data.subject ? data.subject.toUpperCase() : `WARNING - ${data.reason.toUpperCase()}`;
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(headerTitle, 20, 100);

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    let y = 120;

    doc.text(`Dear ${data.staffName.split(' ')[0]},`, 20, y);
    y += 10;
    doc.text("This letter serves as an official written warning regarding your recent conduct.", 20, y);
    y += 10;

    // Details
    doc.setFont("helvetica", "bold");
    doc.text("Incident Details:", 20, y + 10);
    doc.setFont("helvetica", "normal");
    const detailsLines = doc.splitTextToSize(data.details, 170);
    doc.text(detailsLines, 20, y + 20);
    y += 20 + (detailsLines.length * 5);

    // Action
    doc.setFont("helvetica", "bold");
    doc.text("Required Action / Consequences:", 20, y + 10);
    doc.setFont("helvetica", "normal");
    const actionLines = doc.splitTextToSize(data.actionRequired, 170);
    doc.text(actionLines, 20, y + 20);

    y += 40;
    doc.text("Issued By:", 20, y);
    doc.text(data.issuerName || "Management", 20, y + 6);

    // Footer
    const footerY = 280;
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text("POT OF JOLLOF LTD - STRICTLY CONFIDENTIAL", 105, footerY, { align: 'center' });

    if (options.returnBase64) {
        return doc.output('datauristring').split(',')[1];
    } else {
        doc.save(`Warning_${data.staffName.replace(/\s+/g, '_')}_${format(new Date(), 'yyyyMMdd')}.pdf`);
    }
};

export const generateIDCardPDF = async (profile) => {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: [54, 86] // Standard CR80 ID Card Size
    });

    // 1. Front of the Card
    doc.setFillColor(26, 26, 26); // Dark background
    doc.rect(0, 0, 54, 86, 'F');
    
    // Add Logo
    doc.addImage(LOGO_BASE64, 'PNG', 19, 4, 16, 16);
    
    // Header text
    doc.setTextColor(250, 204, 21); // Yellow
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text("POT OF JOLLOF", 27, 24, { align: 'center' });
    doc.setFontSize(5);
    doc.text("STAFF ID CARD", 27, 27, { align: 'center' });

    // Try to load avatar if exists
    let avatarY = 32;
    if (profile.avatar_url) {
        try {
            // Need to convert image url to base64 or add directly if CORS allows. 
            // In a real browser environment, addImage can take a URL, but CORS might block it.
            // Assuming it works:
            doc.addImage(profile.avatar_url, 'JPEG', 14, 30, 26, 26);
        } catch (e) {
            doc.setFillColor(200, 200, 200);
            doc.rect(14, 30, 26, 26, 'F');
        }
    } else {
        doc.setFillColor(200, 200, 200);
        doc.rect(14, 30, 26, 26, 'F');
    }
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.text((profile.full_name || 'Staff Member').toUpperCase(), 27, 62, { align: 'center' });
    
    doc.setTextColor(200, 200, 200);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.text((profile.job_title || profile.title || profile.role || 'Employee').toUpperCase(), 27, 66, { align: 'center' });
    
    doc.setTextColor(250, 204, 21);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text(profile.staff_id || 'N/A', 27, 72, { align: 'center' });
    
    doc.setDrawColor(250, 204, 21);
    doc.setLineWidth(1);
    doc.line(0, 80, 54, 80);
    
    // 2. Back of the Card
    doc.addPage();
    doc.setFillColor(255, 255, 255); // White background
    doc.rect(0, 0, 54, 86, 'F');
    
    doc.setFillColor(26, 26, 26);
    doc.rect(0, 10, 54, 15, 'F'); // Magnetic stripe dummy
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(6);
    doc.setFont("helvetica", "bold");
    doc.text("PROPERTY OF POT OF JOLLOF LTD", 27, 32, { align: 'center' });
    
    doc.setFontSize(5);
    doc.setFont("helvetica", "normal");
    const backText = "This card is the property of Pot of Jollof Ltd. It must be returned upon termination of employment. If found, please return to the nearest police station or to our main office.";
    const lines = doc.splitTextToSize(backText, 46);
    doc.text(lines, 4, 38);
    
    if (profile.emergency_contact_name && profile.emergency_contact_phone) {
        doc.setFontSize(6);
        doc.setFont("helvetica", "bold");
        doc.text("EMERGENCY CONTACT", 27, 55, { align: 'center' });
        doc.setFont("helvetica", "normal");
        doc.text(profile.emergency_contact_name, 27, 60, { align: 'center' });
        doc.text(profile.emergency_contact_phone, 27, 63, { align: 'center' });
    }
    
    doc.save(`IDCard_${(profile.full_name || 'Staff').replace(/\s+/g, '_')}.pdf`);
};

export const generateDocumentPDF = (docData, options = {}) => {
    const doc = new jsPDF();
    // Background Letterhead
    doc.addImage(LOGO_BASE64, 'PNG', 160, 10, 30, 30);
    doc.setDrawColor(0, 0, 0);
    doc.setLineWidth(0.5);
    doc.line(20, 45, 190, 45);

    // Body
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`DATE: ${format(new Date(docData.created_at || new Date()), 'MMMM d, yyyy')}`, 190, 60, { align: 'right' });

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("To:", 20, 60);
    doc.setFont("helvetica", "normal");
    doc.text(docData.staffName || "Staff Member", 20, 66);
    if (docData.staffEmail) doc.text(docData.staffEmail, 20, 72);

    doc.setDrawColor(200, 200, 200);
    doc.line(20, 80, 190, 80); // Divider

    const subjectText = docData.content?.subject || docData.subject;
    if (subjectText) {
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text(subjectText.toUpperCase(), 20, 95);
    }

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    let y = 110;

    doc.text(`Dear ${docData.staffName ? docData.staffName.split(' ')[0] : 'Member'},`, 20, y);
    y += 10;
    
    // Split content text
    const textLines = doc.splitTextToSize(docData.content?.text || '', 170);
    doc.text(textLines, 20, y);
    
    y += (textLines.length * 5) + 30;

    doc.text("Issued By:", 20, y);
    doc.text("POT OF JOLLOF LTD Management", 20, y + 6);
    
    if (docData.status === 'Signed') {
        doc.setTextColor(24, 160, 122); // primary green
        doc.setFont("helvetica", "bold");
        doc.text("DIGITALLY SIGNED AND ACCEPTED", 20, y + 20);
        
        if (docData.signed_at) {
            doc.setFontSize(9);
            doc.text(`Signed At: ${format(new Date(docData.signed_at), 'MMM d, yyyy h:mm a')}`, 20, y + 25);
        }

        if (docData.signature_data) {
            // Draw signature image
            doc.addImage(docData.signature_data, 'PNG', 20, y + 30, 40, 20);
        }
    }

    if (options.returnBase64) {
        return doc.output('datauristring').split(',')[1];
    } else {
        doc.save(`${docData.category}_${docData.document_type}_${format(new Date(), 'yyyyMMdd')}.pdf`);
    }
};

export const generateZReportPDF = (zReportData) => {
    import('jspdf-autotable').then(({ default: autoTable }) => {
        const doc = new jsPDF();
        const secondaryColor = [17, 24, 39]; // Dark gray

        // --- Header ---
        doc.addImage(LOGO_BASE64, 'PNG', 160, 10, 30, 30);
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(20);
        doc.setFont("helvetica", "bold");
        doc.text("END OF DAY REPORT", 20, 25);
        
        doc.setDrawColor(0, 0, 0);
        doc.setLineWidth(0.5);
        doc.line(20, 45, 190, 45);

        // --- Shift Details ---
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        
        const { shift, cashSales, mpesaSales, cardSales, totalSales, otherSales } = zReportData;
        const generatedAt = format(new Date(), 'PPpp');
        
        doc.text(`Generated: ${generatedAt}`, 190, 52, { align: 'right' });
        doc.setFont("helvetica", "bold");
        doc.text("Shift Details", 20, 55);
        
        doc.setFont("helvetica", "normal");
        doc.text(`Shift ID: ${shift.id.slice(0, 8).toUpperCase()}`, 20, 62);
        doc.text(`Cashier: ${shift.cashier_name.toUpperCase()}`, 20, 68);
        doc.text(`Opened: ${format(new Date(shift.opened_at), 'PP p')}`, 20, 74);
        doc.text(`Closed: ${format(new Date(shift.closed_at), 'PP p')}`, 20, 80);
        
        // --- Revenue Breakdown Table ---
        autoTable(doc, {
            startY: 90,
            head: [['Revenue Breakdown', 'Amount (KES)']],
            body: [
                ['Opening Float (Cash)', parseFloat(shift.opening_float).toLocaleString()],
                ['Cash Sales', cashSales.toLocaleString()],
                ['MPESA Sales', mpesaSales.toLocaleString()],
                ['Card Sales', cardSales.toLocaleString()],
                ['Other / Split Sales', otherSales ? otherSales.toLocaleString() : '0'],
            ],
            foot: [['Total Sales Revenue', totalSales.toLocaleString()]],
            theme: 'grid',
            headStyles: { fillColor: secondaryColor, textColor: [255, 255, 255] },
            footStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: 'bold' },
            styles: { fontSize: 10, cellPadding: 5 },
            columnStyles: {
                0: { cellWidth: 100 },
                1: { cellWidth: 50, halign: 'right' }
            }
        });

        const reconciliationY = doc.lastAutoTable.finalY + 15;

        // --- Cash Drawer Reconciliation Table ---
        const expectedCash = parseFloat(shift.expected_cash);
        const actualCash = parseFloat(shift.actual_cash);
        const variance = actualCash - expectedCash;
        
        autoTable(doc, {
            startY: reconciliationY,
            head: [['Cash Drawer Reconciliation', 'Amount (KES)']],
            body: [
                ['Expected Cash in Drawer', expectedCash.toLocaleString()],
                ['Actual Cash Declared', actualCash.toLocaleString()],
                ['Variance (Overage/Shortage)', variance.toLocaleString()],
            ],
            theme: 'grid',
            headStyles: { fillColor: secondaryColor, textColor: [255, 255, 255] },
            styles: { fontSize: 10, cellPadding: 5 },
            columnStyles: {
                0: { cellWidth: 100 },
                1: { cellWidth: 50, halign: 'right', fontStyle: 'bold', textColor: variance < 0 ? [220, 38, 38] : (variance > 0 ? [22, 163, 74] : [0,0,0]) }
            }
        });

        // --- Footer ---
        const finalY = doc.lastAutoTable.finalY + 30;
        doc.setDrawColor(200, 200, 200);
        doc.line(20, finalY, 190, finalY);

        doc.setFontSize(8);
        doc.setTextColor(100, 100, 100);
        doc.text("This report was automatically generated by the ManiPOS System.", 105, finalY + 10, { align: 'center' });
        doc.text("Keep this document for your daily accounting records.", 105, finalY + 15, { align: 'center' });

        doc.save(`Z_Report_${shift.cashier_name.replace(/\s+/g, '_')}_${format(new Date(shift.closed_at), 'yyyyMMdd')}.pdf`);
    });
};

export const generateItemsSoldPDF = (itemsData, dateRangeStr = '') => {
    import('jspdf-autotable').then(({ default: autoTable }) => {
        const doc = new jsPDF();
        const secondaryColor = [17, 24, 39]; // Dark gray

        // --- Header ---
        doc.addImage(LOGO_BASE64, 'PNG', 160, 10, 30, 30);
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(18);
        doc.setFont("helvetica", "bold");
        doc.text("ITEMS SOLD REPORT", 20, 25);
        
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(100, 100, 100);
        doc.text(`Period: ${dateRangeStr || format(new Date(), 'MMMM d, yyyy')}`, 20, 33);
        doc.text(`Generated: ${format(new Date(), 'PPpp')}`, 20, 39);

        doc.setDrawColor(200, 200, 200);
        doc.setLineWidth(0.5);
        doc.line(20, 44, 190, 44);

        // --- Summary Stats ---
        const totalItems = itemsData.reduce((sum, i) => sum + (i.quantity || 0), 0);
        const totalRevenue = itemsData.reduce((sum, i) => sum + (i.totalAmount || 0), 0);

        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(0, 0, 0);
        doc.text(`Unique Items: ${itemsData.length}`, 20, 50);
        doc.text(`Total Units Sold: ${totalItems.toLocaleString()}`, 80, 50);
        doc.text(`Total Revenue: KES ${Math.round(totalRevenue).toLocaleString()}`, 140, 50);

        // --- Table ---
        const tableBody = itemsData.map((item, index) => [
            index + 1,
            item.name || 'Unknown Item',
            item.category || 'General',
            (item.quantity || 0).toLocaleString(),
            `KES ${Math.round(item.totalAmount / (item.quantity || 1)).toLocaleString()}`,
            `KES ${Math.round(item.totalAmount || 0).toLocaleString()}`
        ]);

        autoTable(doc, {
            startY: 56,
            head: [['#', 'Item Name', 'Category', 'Qty Sold', 'Avg Price', 'Total Sales']],
            body: tableBody,
            foot: [['', 'Grand Total', '', totalItems.toLocaleString(), '', `KES ${Math.round(totalRevenue).toLocaleString()}`]],
            theme: 'striped',
            headStyles: { fillColor: secondaryColor, textColor: [255, 255, 255], fontStyle: 'bold' },
            footStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: 'bold' },
            styles: { fontSize: 9, cellPadding: 4 },
            columnStyles: {
                0: { cellWidth: 12, halign: 'center' },
                1: { cellWidth: 'auto' },
                2: { cellWidth: 35 },
                3: { cellWidth: 25, halign: 'right' },
                4: { cellWidth: 30, halign: 'right' },
                5: { cellWidth: 35, halign: 'right' }
            }
        });

        // --- Footer ---
        const finalY = doc.lastAutoTable.finalY + 25;
        doc.setDrawColor(200, 200, 200);
        doc.line(20, finalY, 190, finalY);

        doc.setFontSize(8);
        doc.setTextColor(100, 100, 100);
        doc.text("This Items Sold Report was automatically generated by the POS System.", 105, finalY + 8, { align: 'center' });

        const filenameDate = (dateRangeStr || format(new Date(), 'yyyyMMdd')).replace(/[^a-zA-Z0-9_-]/g, '_');
        doc.save(`Items_Sold_Report_${filenameDate}.pdf`);
    });
};
