import jsPDF from 'jspdf';
import { format } from 'date-fns';
import { LOGO_BASE64 } from './logo';

export const generateZReportPDF = (zReportData) => {
    // We need autoTable for the list
    import('jspdf-autotable').then(({ default: autoTable }) => {
        const doc = new jsPDF();
        
        // Brand Colors
        const primaryColor = [250, 204, 21]; // Yellow
        const secondaryColor = [17, 24, 39]; // Dark gray

        // --- Header ---
        doc.addImage(LOGO_BASE64, 'PNG', 160, 10, 30, 30);
        
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(20);
        doc.setFont("helvetica", "bold");
        doc.text("END OF DAY REPORT", 20, 25);
        
        doc.setDrawColor(0, 0, 0);
        doc.setLineWidth(0.5);
        doc.line(20, 45, 190, 45);

        // --- Shift Details ---
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        
        const { shift, cashSales, mpesaSales, cardSales, totalSales, otherSales } = zReportData;
        const generatedAt = format(new Date(), 'PPpp');
        
        doc.text(`Generated: ${generatedAt}`, 190, 52, { align: 'right' });
        
        doc.setFont("helvetica", "bold");
        doc.text("Shift Details", 20, 55);
        
        doc.setFont("helvetica", "normal");
        doc.text(`Shift ID: ${shift.id.slice(0, 8).toUpperCase()}`, 20, 62);
        doc.text(`Cashier: ${shift.cashier_name.toUpperCase()}`, 20, 68);
        doc.text(`Opened: ${format(new Date(shift.opened_at), 'PP p')}`, 20, 74);
        doc.text(`Closed: ${format(new Date(shift.closed_at), 'PP p')}`, 20, 80);
        
        // --- Revenue Breakdown Table ---
        autoTable(doc, {
            startY: 90,
            head: [['Revenue Breakdown', 'Amount (KES)']],
            body: [
                ['Opening Float (Cash)', parseFloat(shift.opening_float).toLocaleString()],
                ['Cash Sales', cashSales.toLocaleString()],
                ['MPESA Sales', mpesaSales.toLocaleString()],
                ['Card Sales', cardSales.toLocaleString()],
                ['Other / Split Sales', otherSales ? otherSales.toLocaleString() : '0'],
            ],
            foot: [['Total Sales Revenue', totalSales.toLocaleString()]],
            theme: 'grid',
            headStyles: { fillColor: secondaryColor, textColor: [255, 255, 255] },
            footStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: 'bold' },
            styles: { fontSize: 10, cellPadding: 5 },
            columnStyles: {
                0: { cellWidth: 100 },
                1: { cellWidth: 50, halign: 'right' }
            }
        });

        const reconciliationY = doc.lastAutoTable.finalY + 15;

        // --- Cash Drawer Reconciliation Table ---
        const expectedCash = parseFloat(shift.expected_cash);
        const actualCash = parseFloat(shift.actual_cash);
        const variance = actualCash - expectedCash;
        
        autoTable(doc, {
            startY: reconciliationY,
            head: [['Cash Drawer Reconciliation', 'Amount (KES)']],
            body: [
                ['Expected Cash in Drawer', expectedCash.toLocaleString()],
                ['Actual Cash Declared', actualCash.toLocaleString()],
                ['Variance (Overage/Shortage)', variance.toLocaleString()],
            ],
            theme: 'grid',
            headStyles: { fillColor: secondaryColor, textColor: [255, 255, 255] },
            styles: { fontSize: 10, cellPadding: 5 },
            columnStyles: {
                0: { cellWidth: 100 },
                1: { cellWidth: 50, halign: 'right', fontStyle: 'bold', textColor: variance < 0 ? [220, 38, 38] : (variance > 0 ? [22, 163, 74] : [0,0,0]) }
            }
        });

        // --- Footer ---
        const finalY = doc.lastAutoTable.finalY + 30;

        doc.setDrawColor(200, 200, 200);
        doc.line(20, finalY, 190, finalY);

        doc.setFontSize(8);
        doc.setTextColor(100, 100, 100);
        doc.text("This report was automatically generated by the ManiPOS System.", 105, finalY + 10, { align: 'center' });
        doc.text("Keep this document for your daily accounting records.", 105, finalY + 15, { align: 'center' });

        doc.save(`Z_Report_${shift.cashier_name.replace(/\s+/g, '_')}_${format(new Date(shift.closed_at), 'yyyyMMdd')}.pdf`);
    });
};
